// GENERATED by scripts/showcase/generate-stats.mjs (pnpm showcase:stats). Counted from the repository; do not edit.
(function () {
  var SJ = (window.SJ = window.SJ || {});
  SJ.stats = { sourceFiles: 340, sourceLines: 25225, testFiles: 115, testCases: 820, tables: 27, migrations: 15, tasksShipped: 59, docs: 7 };
})();
